### ISSUE TITLE
Dynamics auth issue.

### ISSUE THREAD

**Issue by daanbakker1995** [umbraco/Umbraco.Cms.Integrations#112]
Hi there I am having an connection issue. When pressing connect in the data type, after login in with my credentials the redirect url is not found. I am getting an error that the page: hubspot-forms-auth.umbraco.com cannot be found. 

Anybody seen this before?

The full url is listed here: https://hubspot-forms-auth.umbraco.com/oauth/dynamics/?code=0.AQUAaSrdNopHS0uyX-thf-1ggGVaPIHWz9ZIiSjf_gKq9hoFAL0.AgABAAIAAAD--DLA3VO7QrddgJg7WevrAgDs_wUA9P-9kQSkE0bp0NOdzKJIyUUBU0ePgbFZEocLr42HpAKhzIsCozLKU-aTep0JPE5H-pdicQWHSpN6qycvcVfZrjj8N6a5F1cz_g7IxtwybyiykNzGYkzJgfybmno0IgjwRN6dYwxYPVUQCSRKcgYpLcWSmIfo2M3EIuy5H55FA3fNWXkySQ5c6W0afIHpVApQ8JMbCfIwd_5OkVVV2ZEkXiDpaMbsTMvTHcE2tB5OBDgDvniF270CnkqN-NhjbFX7k8oZsey8T5t6Hr8HHAttDNcKdWNB1ZTy_-u51074Dlmb2LH3DIMkUfydRQFPY9SvhFSVdzkAdyWVnqgVoPIw0vemzgQ9mMIGfmlqx_zp_jB44tgYT9-ZmWNe93naBzHUcOezk7rdQ1E3j62V2S8smvABpXnd10ovnoaQmWoODzWwjZZ3Va0aOc6JF9bU49kuJAriGNrwlZfS6zVwcYmM8MdnOrPmh3tCMEv6AU2s3abKCQ6Ttf31cRoZA40eaQq0w6z8zzP1HlJq1j4CHvXkXvDIY0RTObGcO8W0T73nN7BSwSUjXqgYUheobdwiMfMs3_Gdj0Mvij06OkoIJptEv979PeyE0uTbqplo-bhdnaz5DWhN_19DMcvbwnfPMS-Bgh70BC7iWnmgrzGDd8dbusbST4GPAaMoUnMMl1pV_xIkCA&session_state=e09b6ccc-227e-4d90-8f7d-d9640ec77629#

Umbraco version: 10.4.0
Umbraco.Cms.Integrations.Crm.Dynamics version: 1.2.0

**Comment by daanbakker1995** [comment]
Somehow downgrading the package to 1.1.3 made the authentication work.

**Comment by acoumb** [comment]
Hi @daanbakker1995 ,

Thank you for bringing this to our attention. The issue is now fixed, could you check again with the latest version of the package?

Thank you

**Comment by daanbakker1995** [comment]
Excuses for the late response. We currently have the issue fixed with the 1.1.3 package. I'll contact my colleague if we want to update it to the latest version to test this. Thanks a lot @acoumb!
