### ISSUE TITLE
Needs update for Umbraco 12 compatibility

### ISSUE THREAD

**Issue by ShadeRF** [umbraco/Umbraco.Cms.Integrations#115]
Unable to update to v12 due to version conflict with Umbraco.Cms.Integrations.Crm.Huspot

**Comment by acoumb** [comment]
Hi @ShadeRF ,
I have released version [2.1.1](https://www.nuget.org/packages/Umbraco.Cms.Integrations.Crm.Hubspot/2.1.1) of the package.

Thank you for bringing this to our attention,
Adrian
