### ISSUE TITLE
Integrations.Search.Algolia - Website crash on building index

### ISSUE THREAD

**Issue by rspencer-aimwa** [umbraco/Umbraco.Cms.Integrations#119]
Hello,

Our website is on-
`Umbraco.Cms` version `10.6.0`
`Umbraco.Cms.Integrations.Search.Algolia` version `1.4.0`

I am not quite sure what is happening on this one,
but whenever a content item is saved that exists within an index, or an index tries to get manually rebuilt:

- Umbraco sends a request (PostSave / BuildIndex), it sits on pending for a long time with no response
- times out, halts and crashes the application pool
- Process never succeeds

![image](https://github.com/umbraco/Umbraco.Cms.Integrations/assets/134269042/5da75887-b3e4-4392-9861-45f4b80aeb9f)
![image](https://github.com/umbraco/Umbraco.Cms.Integrations/assets/134269042/8055a5b5-fe99-4f8a-84a8-64690bda150d)

From some testing, I have pinpointed that it only happens on `Umbraco.Cms` version `10.6.0`
And is not dependant on the `Umbraco.Cms.Integrations.Search.Algolia` version

This issue does not occur when reverting back to `Umbraco.Cms` version `10.5.1`

Thank you,
Reece

---
_This item has been added to our backlog [AB#31354](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/31354)_

**Comment by rspencer-aimwa** [comment]
I believe this might be causing the issue:
https://github.com/umbraco/Umbraco-CMS/commit/6bcec26db3701999b502528a40c8eee17a806549#diff-d3af2728c87f1e8b06fcce301da39381569b9b773d1ee52e550cc261001374f0

`GetIndexValues` in `RichTextPropertyEditor.cs` seems to be recursively calling itself

**Comment by rspencer-aimwa** [comment]
No, we are wanting to stay on the LTS version

**Comment by acoumb** [comment]
In that case, while waiting for feedback from the CMS team, you could try extending the indexing engine using your custom implementation as detailed [here](https://docs.umbraco.com/umbraco-dxp/integrations/algolia#extending-the-algolia-indexing) and take a different approach, rather than using the `IDataEditor.PropertyIndexValueFactory` property of the CMS.

**Comment by rspencer-aimwa** [comment]
Thank you for this, we have taken your suggested approach.
I am satisfied with this, and don't think this issue needs to be open here anymore and will close it.

Thank you again,
Reece
