### ISSUE TITLE
Conflict when trying to upgrade past version 12.0.0

### ISSUE THREAD

**Issue by ShadeRF** [umbraco/Umbraco.Cms.Integrations#122]
Hi, thanks for getting the update in for the integrations to work with version 12, however it does not allow any sub version beyond 12.0.0
Trying to upgrade to the latest 12.0.1 causes conflict.

**Comment by acoumb** [comment]
Hi @ShadeRF,

Thank you for your support on this, I have released a new patch for HubSpot (version 3.0.1) fixing the issue.

Adrian
