### ISSUE TITLE
Partial File HubspotForm removed

### ISSUE THREAD

**Issue by ShadeRF** [umbraco/Umbraco.Cms.Integrations#123]
In latest builds, the following file has been removed and causing the error below. Manually restoring the file resolves until re-build.

InvalidOperationException: The partial view '~/App_Plugins/UmbracoCms.Integrations/Crm/Hubspot/Render/HubspotForm.cshtml' was not found. The following locations were searched:
~/App_Plugins/UmbracoCms.Integrations/Crm/Hubspot/Render/HubspotForm.cshtml

**Comment by acoumb** [comment]
Hi @ShadeRF ,
Thank you for reporting this, I have released patch version [3.0.2](https://www.nuget.org/packages/Umbraco.Cms.Integrations.Crm.Hubspot/3.0.2) fixing this.

Regards,
Adrian
