### ISSUE TITLE
Adding a RichText field to index, then update index crashes Umbraco

### ISSUE THREAD

**Issue by danbord** [umbraco/Umbraco.Cms.Integrations#124]
Adding a richText field to Index and building index crashes Umbraco

using Umbraco 12

**Comment by danbord** [comment]
Same issue with ImageCrop field

**Comment by danbord** [comment]
Some finds.  I've been able to fix the Access Violation crash.

In AlgoliaSearchPropertyIndexValueFactory.GetValue, it was crashing on the line :
`var indexValues = dataType.Editor.PropertyIndexValueFactory.GetIndexValues(property, culture, string.Empty, true)`

Seems that overload is deprecated, and suggest that we use the overload that passes the availableCultures.  Passing the availableCultures fixes the Crash.  But we end up with nothing being indexed for that field.

Here's my fix:

need to inject localizationService, then:
```
var allLanguages = _localizationService.GetAllLanguages().Select(l => l.IsoCode);
var indexValues = dataType.Editor.PropertyIndexValueFactory.GetIndexValues(property, culture, string.Empty, true, allLanguages);
```

**Comment by acoumb** [comment]
Hi @danbord ,

After considering the implications of this change to different versions of the CMS, as detailed below, we think that making this change will impact developers using versions of Umbraco `10.3` to `10.5.1`, as well as `11.0.0` to `11.3.1`, and the solution would be to update the Umbraco CMS to the version containing the fix. In your case, updating to `12.1.0` will fix the issue.
![image](https://github.com/umbraco/Umbraco.Cms.Integrations/assets/95346674/f083181a-8116-4837-96fc-71ea8c509a10)

Closing the issue, thank you for your feedback,
Adrian
