### ISSUE TITLE
Crm Hubspot 3.2.0 incompatible with version > 12.0

### ISSUE THREAD

**Issue by ShadeRF** [umbraco/Umbraco.Cms.Integrations#127]
This was fixed in the previous version but appears to be broken again. Unable to upgrade from 3.1.0 to 3.2.0 on Umbraco 12.1.2 due to version conflict.

**Comment by acoumb** [comment]
Hi @ShadeRF ,

I think you are referring to the package version for Umbraco Forms? I've released a new patch with the fix, under version [3.2.1](https://www.nuget.org/packages/Umbraco.Forms.Integrations.Crm.Hubspot/3.2.1).

Thanks for the support,
Adrian
