### ISSUE TITLE
Algoloa Search - Back office rendering issue

### ISSUE THREAD

**Issue by thenexus00** [umbraco/Umbraco.Cms.Integrations#128]
Hi,
I found an issue with how you render the document type list in the Algolia search.

`<uui-ref-node id="navigation" ng-attr-selected="{{contentType.selected || undefined}}" ng-repeat="contentType in vm.manageIndex.contentTypesList" ng-on-open="vm.manageIndex.showProperties(contentType)" name="Navigation" class="ng-scope">`

If you happen to have document type names the same as backoffice components the Umbraco CMS CSS causes a clash with the Umbraco UI.

/umbraco/assets/css/umbraco.min.css

In my case I had a couple of issues where a document type "Navigation" caused the whole list not to render properly because it clashed with: #navigation, .navigation-inner-container in the Umbraco CSS.

My suggestion would be to combine the document name and ID into the ID field.
id="dc_DocumentName_ID" thus id="dc_Navigation_9381" so it wont clash

**Comment by acoumb** [comment]
Hi @thenexus00 ,

Thank you for your help, following your PR, I've released a new [version](https://www.nuget.org/packages/Umbraco.Cms.Integrations.Search.Algolia/1.4.2) of the package containing your changes.

Adrian
