### ISSUE TITLE
Algolia Search - Bad data

### ISSUE THREAD

**Issue by thenexus00** [umbraco/Umbraco.Cms.Integrations#130]
I am going to try to work on these myself (If I can) but...

1. The Custom field type for tags renders the names , Great! But if you have content picker it is rendering - umb://document/ab2001d3116744588317f979d7ee19e3. Again not really good data. The name is what you really need here.

2. Adding a Media picker causes things to crash and produce errors. It simply does not like it. The media URL (absolute) is what it should be able to return.

3. For what Algolia can do, linking into things like mobile apps and so on when you have a page of data the url you return should be an absolute URL, NOT relative.

4. Property type of tags is only rendering the first item

---
_This item has been added to our backlog AB#34932_

**Comment by acoumb** [comment]
Hi @thenexus00 ,

Thank you for your support, let me know if there's anything I can assist you with.

Regards,
Adrian

**Comment by thenexus00** [comment]
> Hi @thenexus00 ,
> 
> Thank you for your support, let me know if there's anything I can assist you with.
> 
> Regards, Adrian

I am struggling a little with the IndexValueFactory
Every property type needs a check to ensure good named data comes through.

Multi tree picker for example should return the name.
At some point  the field selection should be changed so you can choose what Value to return as I am sure some people will want ID's in some cases, names in others etc.

**Comment by thenexus00** [comment]
I have Tag's fixed and I have names rendering for Multiple content picker. I will get these in git on Monday.

There is one big Algolia example with search pages rendering as grouped results. They do this with multiple indexes. This is a great way for the separate data types.
The current implementation has the ability to basically have an index per document types you choose which is great. What it also needs is a filter. To define a property as the filter and a value for the filter.

Say you have category which is a Tag attribute. Choosing this and in a field input typing the word. Only pages with said filter will go into an index. I have this running for another platform. I am not too good with the back office and not across the new UI stuff. If this is a valid Idea it would be good to get this in.
