### ISSUE TITLE
Filtering

### ISSUE THREAD

**Issue by thenexus00** [umbraco/Umbraco.Cms.Integrations#131]
I think this is important.

**A must us "Do not send to Algolia".**

There should be a filter aspect once you select your document type(s) to choose which Attribute is your filter and the provide the value for the filter.

So if you have a toggle and the value is 0 and 0 is what you have set then it will NOT be built into the index. Just as if you were to exclude pages in a local index or google sitemap etc.

With that some examples for search pages in Algoloa have grouped search results with categories and headings. While you can form different results the big examples they have they talk about separating your data into different indexes.

The current implementation has the ability to basically have an index per document types you choose which is great. What it also needs is a filter. To define a property as the filter and a value for the filter.

Say you have category which is a Tag attribute. Choosing this and in a field input typing the word. Only pages with said filter will go into an index. I have this running for another platform. 

**I am not too good with the back office and not across the new UI stuff. If this is a valid Idea it would be good to get this in.**

**Comment by acoumb** [comment]
Hi @thenexus00 ,

If you have this on a different platform, could you share a use case or other specifications to fully understand the expected result?

Thanks,
Adrian

**Comment by thenexus00** [comment]
> Hi @thenexus00 ,
> 
> If you have this on a different platform, could you share a use case or other specifications to fully understand the expected result?
> 
> Thanks, Adrian

I built an integration into Kentico but the platform does not matter.

Sending all data to Algolia and then trying to filter it out on search result rendering is problematic because....

1. You take up more data in Algolia than needed
2. Either through API or Dynamic there is no base control in Algolia to filter or not have results show so you either have to build complex logic in Algolia (which does not always work out) OR you have to pass a value and try to use that when rendering search results.

It is far easier to have Custom field values that, on save of a document or sync the code checks and then applies.

Similar to selecting the fields you want to set there could/should be some control or settings options. You would pick which custom field is your filter. Sync Yes or no. If no then skip that document and do not sync. There are heaps similar Algolia based control features which over time could be expanded to support as well.
It is far easier to manage where data you DO NOT want to be synced is not there in the first place.

**Comment by acoumb** [comment]
Hi @thenexus00 , 

Algolia has a new major release, version [2.0.0](https://www.nuget.org/packages/Umbraco.Cms.Integrations.Search.Algolia/2.0.0).

Details of the updates can be viewed [here](https://docs.umbraco.com/umbraco-dxp/integrations/algolia#version-2.0.0-and-up).

Could you tell me how the new version works for you?

Thanks,
Adrian

**Comment by thenexus00** [comment]
Hi, I will be integrating this into another project soon so I will let you know. I made several modification to suit on the previous project so I do not want to mess with that just yet as it is in review with the client.

**Comment by acoumb** [comment]
Hi @thenexus00 ,

There have been several updates on `Algolia`, feel free to test them out. I will be closing this for due to low activity.

Thanks,
Adrian
