### ISSUE TITLE
Semrush Integration outdated?

### ISSUE THREAD

**Issue by marcoteodoro** [umbraco/Umbraco.Cms.Integrations#132]
I'm trying to use the Umbraco.Cms.Integrations.SEO.Semrush and follow the documentation (https://docs.umbraco.com/umbraco-dxp/integrations/semrush). 

The first issue I found was that after a successful oath process, I had an exception while loading any content node. Looking at the code, I realize that the baseUrl was not set on the app settings. (https://github.com/umbraco/Umbraco.Cms.Integrations/blob/76a437fb67fd7354418cec55ed53dc153634a604/src/Umbraco.Cms.Integrations.SEO.Semrush/Constants.cs#L20), this is not identified on the documentation, perhaps something to be included to avoid similar difficulties? Is this the correct endpoint? "BaseUrl": "https://api.semrush.com/"?

After setting this, I no longer have the error but constantly get a null result from the APIs. 

Further investigation I found that the slug used is {0}api/v1/keywords/{1}?access_token={2}&phrase={3}&database={4}, but I can't find this API version available on sem rush developers site. https://developer.semrush.com/api/basics/introduction/#api-versioning-changelog/ Just versions 3 and 4 are listed there. 

Do you happen to know if this package is still usable? as is, or it's missing an update? 

Thanks

---
_This item has been added to our backlog [AB#33088](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/33088)_

**Comment by acoumb** [comment]
Hi @marcoteodoro ,

As base URL you will need to use `https://oauth.semrush.com/`.

A minimal configuration for the package to work would be this one:
```
"SEO": {
  "Semrush": {
    "Settings": {
      "BaseUrl": "https://oauth.semrush.com/"
    }
  }
}
```

**Comment by marcoteodoro** [comment]
thanks @acoumb ! maybe the Umbraco documentation could be updated with this info https://docs.umbraco.com/umbraco-dxp/integrations/semrush

**Comment by acoumb** [comment]
Thanks, will do so.
