### ISSUE TITLE
Algolia Search - Indexing of non-string values

### ISSUE THREAD

**Issue by geann** [umbraco/Umbraco.Cms.Integrations#151]
Sometimes we need to index non-string fields in Algolia. For example, we have a MultiNodeTreePicker category field and we want to index it as an array of names or GUIDs. Currently we have to serialize this data because the method `GetValue()` of `AlgoliaSearchPropertyIndexValueFactory` can return only string values. 
The problem with this approach is that it is then stored as a text value in Algolia rather than an object:

![image](https://github.com/umbraco/Umbraco.Cms.Integrations/assets/4091048/7eb7d7f8-7f83-4a58-bee3-5affaa8067b1)

Even though full text search by categories works ok, there is an issue with facets as Algolia doesn't parse serialised objects and instead treats them as text:
![image](https://github.com/umbraco/Umbraco.Cms.Integrations/assets/4091048/d51fedd0-523c-4287-9d31-2b3c7b4d7f98)

I tracked usage of string values down to the class [Record.cs](https://github.com/umbraco/Umbraco.Cms.Integrations/blob/main/src/Umbraco.Cms.Integrations.Search.Algolia/Models/Record.cs) where the `Data` property is of type `Dictionary<string, string>`. Do you think this property can be changed to `Dictionary<string, object>` to cater for non-string values?

---
_This item has been added to our backlog AB#34719_

**Comment by thenexus00** [comment]
It is a json string that you need so that comes into the Algolia search objects which can process in there. I have internal fixes and I did do a pull request so things like Multi tree node picker renders out the name. You then do work in your Algolia to handle that.

**Comment by acoumb** [comment]
Hi @geann ,

Thank you for the reported issue and your [PR](https://github.com/umbraco/Umbraco.Cms.Integrations/pull/152). 

I've done some testing of different use cases and as a result we would need to prepare in the coming weeks a new version of the package that will provide additional converters for sending data to Algolia, and options for developers to manage the converters themselves, by adding new or removing existing ones.

I will update here with the progress.

Thank you,
Adrian

**Comment by geann** [comment]
That's great, thank you @acoumb!

**Comment by acoumb** [comment]
Hi @geann ,

We have released version [2.0.0](https://www.nuget.org/packages/Umbraco.Cms.Integrations.Search.Algolia/2.0.0) with changes to the way converters work (more details [here](https://github.com/umbraco/Umbraco.Cms.Integrations/pull/154)). 

Please update to the new version and let me know how it goes.

Thank you,
Adrian
