### ISSUE TITLE
Dynamics 365 - No Forms Showing in Form Picker

### ISSUE THREAD

**Issue by ben-umble** [umbraco/Umbraco.Cms.Integrations#176]
Hi,

I'm having trouble getting Dynamics 365 forms to show up in my form picker.

1. I've double and triple-checked the `HostUrl` and `ApiPath` which are correct.
2. I'm able to authenticate
3. I've checked that the domains are verified
4. I've checked that external form embedding is enabled for the relevant domains

The image belows shows successful connection (hence the `Revoke` button being enabled).

![image](https://github.com/umbraco/Umbraco.Cms.Integrations/assets/102685581/69e30037-8ad3-49c8-acdd-f6a2580a693a)

This image shows the request returning a `200`:

![image](https://github.com/umbraco/Umbraco.Cms.Integrations/assets/102685581/e9307a97-119e-4e39-b6cc-effa83d33c0d)

And finally the response:

![image](https://github.com/umbraco/Umbraco.Cms.Integrations/assets/102685581/16a2a044-f909-4282-a3a3-bf020d8972ba)

From the Dynamics side, you can see the form I'm trying to embed:

![image](https://github.com/umbraco/Umbraco.Cms.Integrations/assets/102685581/f48711d1-0b53-48d6-a8a2-58fbd877a882)

I can't see any other settings or configuration that I'm missing - what am I doing wrong here?

Thanks,

Ben

**Comment by ben-umble** [comment]
A small update:

I've done some digging and tried getting forms directly from Dynamics365 which returns nothing, but I can get the forms from a different endpoint.

It looks like this plugin uses: `{hostUrl}/api/data/v9.2/msdyncrm_marketingforms` which doesn't return forms but a different endpoint I found does `{hostUrl}/api/data/v9.2/msdynmkt_marketingforms`.

I suspect this is my lack of Dynamics 365 knowledge, I'm not sure how these forms vary but the client does need these embedding on the website.

So at this point, perhaps just some dialog on whether it's possible to support these other types of forms.

**Comment by acoumb** [comment]
Hi @ben-umble ,

Indeed, Microsoft moved in [July 2023](https://learn.microsoft.com/en-us/dynamics365/customer-insights/journeys/transition-overview) from outbound marketing to real-time, causing the previous API path `msdyncrm_marketingforms` to not return the proper forms.

I am working on an update to address this situation, and I will let you know as soon as the new version of `Dynamics` is released.

Regards,
Adrian

**Comment by acoumb** [comment]
Hi @ben-umble ,

I have released a new version of the Dynamics integration - [1.3.3](https://www.nuget.org/packages/Umbraco.Cms.Integrations.Crm.Dynamics/1.3.3) with support for `Real-Time` forms.

Please make sure your Dynamics forms are published, as described [here](https://learn.microsoft.com/en-us/dynamics365/customer-insights/journeys/real-time-marketing-form-create#publish-your-form) by Microsoft.

Thank you for bringing this to our attention,
Adrian
