### ISSUE TITLE
ActiveCampaign only returns 20 forms

### ISSUE THREAD

**Issue by AndersBrohus** [umbraco/Umbraco.Cms.Integrations#180]
We face an issue where the ActiveCampaign Form Picker only returns 20 forms, even though there 42 forms created.
Searching does not work since it just filters in the already returned forms.

**Comment by acoumb** [comment]
Hi @AndersBrohus ,

I have released version [2.0.4](https://www.nuget.org/packages/Umbraco.Cms.Integrations.Crm.ActiveCampaign/2.0.4) of the package with support for pagination.

Thank you for bringing this to our attention,
Adrian

**Comment by AndersBrohus** [comment]
Thanks alot @acoumb :)
