### ISSUE TITLE
Algolia - TinyMCE not indexed in Umbraco 13 with 2.1.4 Algolia

### ISSUE THREAD

**Issue by gardarthorsteins** [umbraco/Umbraco.Cms.Integrations#188]
When indexing TinyMCE properties the value is always return empty to algolia.

This line here is the problem inside of AlgoliaSearchPropertyIndexValueFactory

`var indexValues = propertyEditor.PropertyIndexValueFactory.GetIndexValues(property, culture, null, true);`

The values are in the property but indexValues return empty string.

I'm guessing the issue is the Umbraco update to the TinyMCE property lately, it returns an json object now instead of a string.

I was hoping to fix the problem temporarily by creating a converter for TinyMCE properties but I would need the property data be passed into it to work with the values my self.

I think that passing the property to the converter would be very powerful so we could not only do specific thing with property editors but also target specific ones with the alias or use the raw values or self.

**Comment by acoumb** [comment]
Hi @gardarthorsteins ,

I have included this update with today's [2.1.5](https://www.nuget.org/packages/Umbraco.Cms.Integrations.Search.Algolia/2.1.5) patch release of Algolia.

Thanks,
Adrian
