### ISSUE TITLE
modules-configuration.controller.js missing

### ISSUE THREAD

**Issue by remkovb** [umbraco/Umbraco.Cms.Integrations#206]
In package.manifest there is this line:

"~/App_Plugins/UmbracoCms.Integrations/Crm/Dynamics/js/modules-configuration.controller.js",

This file is missing?

---
_This item has been added to our backlog AB#43078_

**Comment by acoumb** [comment]
Hi @remkovb ,

Thank you for spotting this, I've corrected the references of the manifest with minor version [1.3.6](https://www.nuget.org/packages/Umbraco.Cms.Integrations.Crm.Dynamics/1.3.6) of the package.

Regards,
Adrian
