### ISSUE TITLE
Migration of old indicies to Umbraco 14

### ISSUE THREAD

**Issue by evaHopNltg** [umbraco/Umbraco.Cms.Integrations#222]
When we upgrade AlgoliaSearch, from 13 to 14, our old indicies doesn't work in the dashboard beacause the datamodel have changed. 

When I look in the migration script, the only concern are if the table exists or not. 

---
_This item has been added to our backlog AB#45268_

**Comment by acoumb** [comment]
Hi @evaHopNltg ,
I've released version [`3.2.0`](https://www.nuget.org/packages/Umbraco.Cms.Integrations.Search.Algolia/3.2.0) of Algolia, which addresses this issue.

Regards,
Adrian
