### ISSUE TITLE
All properties even thus that are not selected are including when building or saveing an index in version 14

### ISSUE THREAD

**Issue by evaHopNltg** [umbraco/Umbraco.Cms.Integrations#223]
When building an index against version 14 all properties are included, even thus that have select = false. Have found out that it's due to the changes in the datamodel. One solution is to add check if selected are true when calling ContentRecordBuilder

	var contentRecordBuilder = new ContentRecordBuilder(
			userService,
			urlProvider,
			algoliaSearchPropertyIndexValueFactory,
			recordBuilderFactory,
			umbracoContextFactory,
			algoliaGeolocationProvider)
		.BuildFromContent(contentItem, (p) => contentDataItem.Properties.Any(q => q.Alias == p.Alias && q.Selected));

If I try to index a property of type BlockGrid or BlockList, I get system error. 

---
_This item has been added to our backlog AB#45267_

**Comment by acoumb** [comment]
Hi @evaHopNltg ,
Thank you for bringing this to our attention. I have fixed the issue in the latest minor release of Algolia - [`3.2.0`](https://www.nuget.org/packages/Umbraco.Cms.Integrations.Search.Algolia/3.2.0)

Regards,
Adrian
