### ISSUE TITLE
[URL Inspection Tool] Possible Site Url Bug?

### ISSUE THREAD

**Issue by AaronSadlerUK** [umbraco/Umbraco.Cms.Integrations#28]
When using the URL Inspection Tool, I get a 403 permission denied API response if the site url is set as:

`https://domain.com`

However it works if I change it to (with the added forward slash):

`https://domain.com/` 

How is it determining the SiteUrl?
Should it have a forward slash at the end as standard?

See this issue on the Google Forum which is how I found the fix:
https://support.google.com/webmasters/thread/150197528?hl=en&msgid=150238355

**Comment by acoumb** [comment]
Hi Aaron, and thank you for bringing this to our attention. Firstly, could you tell me the format of your web property [here](https://search.google.com/search-console) , is it `https://domain.com` or `https://domain.com/` ?

**Comment by AaronSadlerUK** [comment]
It is `https://domain.com/` in the Google Search console.

Google themselves added the / back when it was created.

On looking nearly all of the sites in my search console have the / appended on the end.

**Comment by AaronSadlerUK** [comment]
On checking again... A **Domain property** does not have a / at the end however a **URL prefix** property does have a / at the end.

**Comment by acoumb** [comment]
The `InspectionUrl` parameter sent with the API request is used by Google for web property ownership verification.
Maybe the [blog post](https://umbraco.com/blog/integrating-umbraco-cms-with-google-search-console-url-inspection-tool/) covering the integration will provide more information.

**Comment by acoumb** [comment]
As discussed, this was resolved by the configuration of the Google Search Console web property, so will now close the issue.
