### ISSUE TITLE
Hubspot authentication blocks editor

### ISSUE THREAD

**Issue by FransdeJong** [umbraco/Umbraco.Cms.Integrations#30]
If you use the form picker for Hubspot with OAuth you need rights to the datatype to login to hubspot and pick forms.

Editors without settings rights can't add form without developer help. This seems a bit unfriendly.
Would it be possible to, instead of throwing only a warning, to enable editors to login from the property editor?

**Comment by acoumb** [comment]
Hi Frans, thank you for your feedback. I have released version [1.1.2](https://www.nuget.org/packages/Umbraco.Cms.Integrations.Crm.Hubspot/1.1.2) of the package covering your use case.
