### ISSUE TITLE
Add Shopify product id

### ISSUE THREAD

**Issue by richard-arkom** [umbraco/Umbraco.Cms.Integrations#31]
Would be really useful if someone could add the Shopify product Id to the ShopifyProductPickerValueConverter / ProductViewModel so we can access it on our pages.

Don't think it would take very long.

Cheers

**Comment by richard-arkom** [comment]
Hi,

Thank you for adding in the Product Id field, it will be so useful.

Quick question, how long is it before the version available in the NuGet Package Manager will include the extra field, or is there another way I can install the new version.

Cheers

**Comment by acoumb** [comment]
Hi Richard,

I have released version [1.0.2](https://www.nuget.org/packages/Umbraco.Cms.Integrations.Commerce.Shopify/1.0.2) of the package that includes the _Product Id_ and an update to the asynchronous call to Shopify API in value converter.

I will now close the issue, thank you for your feedback!
