### ISSUE TITLE
Add constants for property editors

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco.Cms.Integrations#48]
I think it would be great to add the property editor aliases as constant similar to in Umbraco core, e.g. the Hubspot form picker:

Currrently `Umbraco.Cms.Integrations.Crm.Hubspot.FormPicker` is hardcoded twice here:
https://github.com/umbraco/Umbraco.Cms.Integrations/blob/main/src/Umbraco.Cms.Integrations.Crm.Hubspot/Editors/FormPickerValueConverter.cs#L19

and here:
https://github.com/umbraco/Umbraco.Cms.Integrations/blob/main/src/Umbraco.Cms.Integrations.Crm.Hubspot/HubspotFormPickerPropertyEditor.cs#L12

There is already a few other constants here:
https://github.com/umbraco/Umbraco.Cms.Integrations/blob/main/src/Umbraco.Cms.Integrations.Crm.Hubspot/Constants.cs

Furthermore the "Pickers" group here could eventually use the constant from `Umbraco.Cms.Core.Constants.PropertyEditors.Groups.Pickers` (slightly different namespace in Umbraco 8):
https://github.com/umbraco/Umbraco.Cms.Integrations/blob/main/src/Umbraco.Cms.Integrations.Crm.Hubspot/HubspotFormPickerPropertyEditor.cs#L15

**Comment by bjarnef** [comment]
Btw. is it possible to possible from a form guid or does it need to entire HubSpotForm model? E.g. it passing in form guid to a Vue component.

E.g. there is a help to render the selected Hubspot form:

```
@Html.RenderHubspotForm(Model.HubspotForm)
```

But can we render it from a known Guid?

```
var guid = Guid.Parse("9ac95f04-a658-467d-936f-4b0a726eb3ca")
// Render Hubspot form
```

or 

```
var guid = Guid.Parse(Model.HubspotForm.Guid)
// Render Hubspot form
```

Currently we have a project using a Vue component where form guid (hardcoded) is passed into an API Controller method like this:

```
[HttpGet]
public HttpResponseMessage getForm(string formId)
{
    string hubspotApiKey = "something-secret";
    string url = string.Format("https://api.hubapi.com/forms/v2/forms/{0}/?hapikey={1}", formId, hubspotApiKey);

    using (WebClient wc = new WebClient())
    {
        var json = wc.DownloadString(url);
        var jObject = JsonConvert.DeserializeObject<RootObject>(json);

        var response = Request.CreateResponse(HttpStatusCode.OK, jObject , "application/json");
        return response;
    }
}
```

**Comment by acoumb** [comment]
Hi @bjarnef 
When HubSpot introduced the EU data centers, this affected the form rendering of the forms. To support both scenarios the view model passed to the view contains the source of the JS script as well as some mandatory fields for HubSpot to initialize the JavaScript objects: region, portal ID and the form ID.
Does this answer your question?

**Comment by bjarnef** [comment]
Hi @acoumb 

Okay, is it still possible to fetch the JSON as today, but it seems starting November 30, 2022, HubSpot API keys will no longer be able to be used as an authentication method to access HubSpot APIs as used in https://github.com/umbraco/Umbraco.Cms.Integrations/issues/48#issuecomment-1260799441

https://developers.hubspot.com/docs/api/developer-guides-resources
https://developers.hubspot.com/docs/api/migrate-an-api-key-integration-to-a-private-app

Currently it seems the Vue component fetch e.g. `portal` from the mentioned API method and render to from JSON using `vue-json-schema-form`:
![image](https://user-images.githubusercontent.com/2919859/192960946-94df5a3a-4f16-4483-b8c4-680ff8b9e7f5.png)

It seems this it currently using "v2" https://legacydocs.hubspot.com/docs/methods/forms/v2/get_form but I noticed there's also a newer "v3" : `GET
/marketing/v3/forms/{formId}`
https://developers.hubspot.com/docs/api/marketing/forms

**Comment by bjarnef** [comment]
@acoumb regarding the access token saved to the database https://umbraco.com/blog/integrating-umbraco-cms-with-hubspot-forms/ is this refreshed when expired? From what I understand it previous expired after 6 hours, but it seems to have changed to 30 minutes? https://developers.hubspot.com/changelog/upcoming-expiration-of-oauth-access-tokens-is-changing

It seems the "old" way using `hapiKey` query parameter then need to send access token in `Authorization` header instead:
https://developers.hubspot.com/docs/api/migrate-an-api-key-integration-to-a-private-app#update-the-authorization-method-of-your-integration-s-api-requests

**Comment by acoumb** [comment]
@bjarnef yes, it is refreshed when an _Unauthorized_ response is retrieved from HubSpot.
I have released a new version of the package [here](https://www.nuget.org/packages/Umbraco.Cms.Integrations.Crm.Hubspot/1.1.3) adding constant values.
Let me know if there is anything else I can help you with.

**Comment by bjarnef** [comment]
Great, I think we can close this issue then.
For this project the client chosen to go with a private app to request the forms using then access token as it otherwise required a bit more work to first upgrade to Umbraco 8.5.4+
