### ISSUE TITLE
Umbraco 11 Compatibility

### ISSUE THREAD

**Issue by ShadeRF** [umbraco/Umbraco.Cms.Integrations#63]
Hi, is there an ETA on updates for Umbraco 11 compatibility? The marketplace currently shows the integration as Umbraco 11 compatible, however, installation of the package causes the site to bomb.
![hubspotumb11](https://user-images.githubusercontent.com/20115489/206746612-2abfe5f5-29e0-44f1-84b0-c9735498158f.png)

**Comment by acoumb** [comment]
Hi @ShadeRF 
Thank you for bringing this to our attention, I will run some tests and get back to you as soon as possible.

**Comment by acoumb** [comment]
Hi @ShadeRF 
I have released version [1.1.6](https://www.nuget.org/packages/Umbraco.Cms.Integrations.Crm.Hubspot/1.1.6) with support for Umbraco 11.
Please update your package version and let me know how it works.
Thank you

**Comment by ShadeRF** [comment]
Hey @acoumb 
The update does get rid of the startup errors; however, now receiving the following error on all pages where I am trying to render the Hubspot forms. These were not changed from my Umbraco 10 project.

![2022-12-14 10_43_29-Internal Server Error and 1 more page - Personal - Microsoft​ Edge](https://user-images.githubusercontent.com/20115489/207641911-e946f544-6ba9-4ed0-9f1f-ad07804c43ae.png)

**Comment by ShadeRF** [comment]
@acoumb Just looping back. Any update here?

**Comment by acoumb** [comment]
Hi @ShadeRF , I've tested this and could not replicate the issue. From the looks of it, I would say that you are passing a string argument to the render method.
For example, passing the string value:
![image](https://user-images.githubusercontent.com/95346674/210786154-3bde8867-2c96-4f52-be03-33bc98022fcc.png)

Could you review the configuration of the document type and get back to me?
Thank you.

**Comment by ShadeRF** [comment]
@acoumb I blew my whole upgrade project out of the water as I could not track down the issue and upon doing a fresh upgrade to 11 things now work as they should. I couldn't tell you what caused it but all is well. Thanks so much for looking into this!
