### ISSUE TITLE
HubSpot API-key sunset

### ISSUE THREAD

**Issue by lars-erik** [umbraco/Umbraco.Cms.Integrations#65]
HubSpot has deprecated the use of the "hapikey" querystring parameter since november 30th.  
The new "way" is to create a private app and send it's "secret" as a bearer token.  
PR incoming. 👼

**Comment by acoumb** [comment]
Hi @lars-erik 
I have released version [2.0.0](https://www.nuget.org/packages/Umbraco.Cms.Integrations.Crm.Hubspot/2.0.0) of HubSpot for Umbraco CMS containing your changes.
I will be closing this now, feel free to reach out if you have other input.
Thank you!
