### ISSUE TITLE
Core projects/nuget packages

### ISSUE THREAD

**Issue by AndersBrohus** [umbraco/Umbraco.Cms.Integrations#69]
Hi :)

Is there any chance we can get Core projects/nuget packages? :)

We are splitting our Umbraco models into a separated project, but are currently facing some issues because of the ActiveCampaign integration, since the only way to get the dll file into our models project is by referencing it from our build project - It works locally but not Azure 🙈

**Comment by acoumb** [comment]
Hi @AndersBrohus 

I've released version [2.0.0](https://www.nuget.org/packages?q=umbraco.cms.integrations.crm.activecampaign) of the package with split versions.

I will close this for now, let me know if you have any input.

Thank you
