### ISSUE TITLE
Algolia Integration - Unable to add Document Types on Create Index Definition panel

### ISSUE THREAD

**Issue by ANT-GBR** [umbraco/Umbraco.Cms.Integrations#70]
I'm using Umbraco 10.3.2 and I can't select Document Types on the Create Index Definition panel because the editor is not loading:

![image](https://user-images.githubusercontent.com/1932798/210815558-b6bbc798-ae5e-4558-9c49-e2b541032f6c.png)

Thanks
Tony

**Comment by acoumb** [comment]
Hi Tony,

Could you tell me which version of Umbraco are you using?

**Comment by ANT-GBR** [comment]
Hi Adrian,

I'm using Umbraco 10.3.2 and Umbraco.Cms.Integrations.Search.Algolia 1.0.0.

Thanks
Tony

**Comment by d-gibbs** [comment]
Hey @acoumb, can you reproduce this issue in Umbraco v11? We have similar problem, although I don't see any console errors, the document types control just doesn't load.

Thanks

**Comment by d-gibbs** [comment]
That does indeed seem to be the problem as if I create a content type at the root it appears in the control as expected:

![image](https://user-images.githubusercontent.com/59481722/211846439-6b18bdda-3eee-4678-8a6e-7681d258b758.png)

I think it needs to account for folders/nesting for it to work correctly.

Thanks

**Comment by acoumb** [comment]
Thanks for clarifying this, I will take your input into consideration and address the matter.

**Comment by acoumb** [comment]
Hi @d-gibbs ,
I've release version [1.1.1](https://www.nuget.org/packages/Umbraco.Cms.Integrations.Search.Algolia/1.1.1) of the package with updates to content type retrieval.
I am closing this now, let me know if you have other input.
