### ISSUE TITLE
Unable to connect to Dynamics 365 when creating Data Type

### ISSUE THREAD

**Issue by ben-umble** [umbraco/Umbraco.Cms.Integrations#77]
Hi,

I'm trying to set up the Dynamics 365 Form Picker property editor for a client website but when I try to connect, it throws a generic error message:

`Dynamics Configuration: Error: An unexpected error occurred.`

I don't get any more information from the error unfortunately, here's the things that I've tried:

1. Tried with an admin user who has full permissions for the entire account
2. Ensured the DNS of the domain is valid
3. Triple-checked my configuration values in the `appSettings.json` file

I'm using the following versions of each platform/package:

1. Umbraco: `9.5.4`
2. Umbraco.Cms.Integrations.Crm.Dynamics: `1.1.2`

Please let me know if you need more information on this :)

Thanks,

Ben

**Comment by mkalinov** [comment]
Hi guys, 
I have exactly same issue but in higher Umbraco version:
Umbraco 10.3.2
Forms 10.2.2
Deploy 10.1.2

I see my deployment logs, but there are no logs for the error though

**Comment by acoumb** [comment]
Hi @ben-umble , @mkalinov ,
And thank you for bringing this to our attention. The key of the Azure App expired and authorization didn't go through.

I have renewed the key and you can use the package again, no other updates required on your part.

I will release though in the next days a minor patch with a handle of the _Unauthorized_ exception, to provide more clarity to the user.

I will be waiting for your confirmation, then I will close this.

Thank you.

**Comment by mkalinov** [comment]
Good morning @acoumb 
Thanks for the update! I confirm it works now for me.

**Comment by mkalinov** [comment]
@acoumb 
a question,
As I see u use custom types and Umbraco Integrations Azure App to make the picker work.
It doesn't looks reliable security wise, as Umbraco app has full access to customer data and we are fully dependent on u, as we just witnessed with key expiration.
We definitely do OAuth directly to crm api, can u please, refer us to any tutorial how to do a custom data type in Umbraco platform?
 

![image](https://user-images.githubusercontent.com/10182226/214093876-d525dd2a-aaa5-4d28-b481-a62c17166f58.png)

**Comment by acoumb** [comment]
Hi,

Is [this](https://docs.umbraco.com/umbraco-cms/tutorials/creating-a-property-editor) what you're referring to?

Regarding the authentication process, all providers that use OAuth have a server of their own to handle authorization and a similar implementation. In case of Dynamic, Microsoft requires the use of a specific application registered in Azure, with a setup for branding and properties, as well as a set of permissions.

With our `Umbraco Integrations`  app we facilitate the user to start using the package out-of-the-box, without worrying about Azure setup. All authorization is then managed through our [OAuth Proxy](https://umbraco.com/blog/integrating-umbraco-cms-with-hubspot-forms/).

**Comment by ben-umble** [comment]
Thanks @acoumb - worked a treat!

Is this likely to happen again in the future or should this now auto-renew?

**Comment by acoumb** [comment]
No, this is now being taken care for the future. 
I am closing this now. 

Thank you!
