### ISSUE TITLE
The list of forms from Dynamics 365 is not populated

### ISSUE THREAD

**Issue by mkalinov** [umbraco/Umbraco.Cms.Integrations#79]
Hi Umbraco team.
We follow this article to integrate our Umbraco to Dynamics marketing:
https://umbraco.com/blog/integrating-umbraco-cms-with-microsoft-dynamics-365-marketing-forms/

We installed integration solution, deployed deployed to portal, did all steps in crm and Azure with domain registration and authentication.
Unfortunately, no drop down appears in the page representing data type:
![DataType_NoPages](https://user-images.githubusercontent.com/10182226/215349123-ab0acb5b-2ea4-4c41-a4e9-e34bb398bebb.JPG)

Any idea why we cannot see list of forms?

We have checked the open source solution. The call below returns forms fine if we do it via crm or Postman:

![Method](https://user-images.githubusercontent.com/10182226/215349950-e3c21bb3-f5d2-472b-94e0-d9cd9859dc37.JPG)

We did not find a way to trace requests with fiddler or debug it in website.
Here Crm related pages to check:
![ActiveDomains](https://user-images.githubusercontent.com/10182226/215350221-7a34e5e5-10fa-4dc7-af24-758635d44884.JPG)

![livedomai](https://user-images.githubusercontent.com/10182226/215350229-514ba9b4-599b-46ec-a67b-3f19b8d376d2.JPG)

![FormsLive](https://user-images.githubusercontent.com/10182226/215350283-f59f15c3-431d-4ce0-9f5f-522d183aa300.JPG)

![FormHostin](https://user-images.githubusercontent.com/10182226/215350254-912fad47-02c5-4abc-83aa-acfa1358fb5a.JPG)

![Page](https://user-images.githubusercontent.com/10182226/215350272-f42fb1e5-36f3-48f9-8263-b04e08fb85cc.JPG)

**Comment by acoumb** [comment]
Hi @mkalinov ,

I am seeing in your screenshots the data type configuration view, but not the property editor. Once the data type is created and added to a document type, if the API returns the list of forms, then the forms should be listed in the property editor overlay view.

Something like this:
![2023-01-31_13-16-25](https://user-images.githubusercontent.com/95346674/215746771-0773077a-838b-402d-a7d1-f875baf02edb.png)
![2023-01-31_13-16-41](https://user-images.githubusercontent.com/95346674/215746825-812a92dd-3006-4b13-a891-6bacba3a1bd4.png)

Could you tell me how is yours looking?

Thank you,
Adrian

**Comment by mkalinov** [comment]
Thanks @acoumb,
Here is my:
![image](https://user-images.githubusercontent.com/10182226/215950204-33a61792-8387-4e76-9250-b4aa96d47e7b.png)

**Comment by acoumb** [comment]
Looks alright, but then in the `Content` area you will be able to access the forms:
![2023-01-31_13-16-25](https://user-images.githubusercontent.com/95346674/216001765-738274e1-ad03-46ae-998e-b9af0b8510c2.png)

**Comment by mkalinov** [comment]
Hmm, there is no content on the home

![image](https://user-images.githubusercontent.com/10182226/216169016-ef423c7b-3ebf-40b3-b7c4-7bee8b55b6fd.png)

**Comment by mkalinov** [comment]
I figured out where to add the property. Now it shows security error:
![image](https://user-images.githubusercontent.com/10182226/216414099-c26d8753-f6e5-460a-9c3a-2a723b57a771.png)

**Comment by acoumb** [comment]
Hi,

I will fix this and include it in a patch coming the next days.

**Comment by acoumb** [comment]
@mkalinov could you also specify which version of the package you are using, and the Umbraco version? 
I can see that the latest version of Dynamics integration hold a fix for this issue.
Thank you

**Comment by mkalinov** [comment]
Here is the versions installed. Dynamics integration is on latest as I can see.
There are some updates for other packages. I tried to update them - few failed ion install, one installed but compilation was corrupted.

![image](https://user-images.githubusercontent.com/10182226/217010911-33257602-96cd-4a3d-b22c-8e65b51f5a7c.png)

**Comment by mkalinov** [comment]
I figured out that if I try to move from 10 to 11 I need to upgrade .net6 to .net7. Even after .net version upgrade any package installation , except  Umbraco Forms, fails. Any tutorial how to move it on?

**Comment by acoumb** [comment]
Hi @mkalinov 

I have released patch version [1.1.3](https://www.nuget.org/packages/Umbraco.Cms.Integrations.Crm.Dynamics/1.1.3) of the package fixing the issue reported here:
> I figured out where to add the property. Now it shows security error: ![image](https://user-images.githubusercontent.com/10182226/216414099-c26d8753-f6e5-460a-9c3a-2a723b57a771.png)

Regarding your last comments, Umbraco 10 works on .NET6, and version 11 on .NET7, any version of Umbraco you choose is fine, you just need to the versions compatibility for the packages.

Thank you

**Comment by acoumb** [comment]
Hi @mkalinov ,

Could you tell me if there is anything else I can assist you with here?

Thanks,
Adrian

**Comment by mkalinov** [comment]
Thanks a lot for ur help, Adrian,

We're working on our own way to connect with powerapps.
I'll yell for help if something pops up :)

Best regards, Michael.
