### ISSUE TITLE
Integrations.Search.Algolia - Index rebuild doesn't handle complex types e.g. MediaWithCrops

### ISSUE THREAD

**Issue by d-gibbs** [umbraco/Umbraco.Cms.Integrations#82]
Hi,

I'm using `Umbraco.Cms.Integrations.Search.Algolia 1.1.1` and in the process of implementing site search. I have set up a basic search index in the backend and have selected a number of fields to be included, one of which is an image field which Umbraco treats as a `MediaWithCrops` object.

I'm finding that the indexer is treating these fields as simple strings where ideally we'd like to get back a path to the media item.

Example:

![image](https://user-images.githubusercontent.com/59481722/216632954-e42894c2-effa-477f-a7f3-431029386d89.png)

Is this something the plugin is capable of out of the box? If not, does the plugin have a way of intercepting the rebuild event on certain document types so that we can add this logic ourselves?

Thank you

**Comment by acoumb** [comment]
Hi @d-gibbs ,

Could you tell me what editor are you using to get this payload in Algolia?

My `Image Media Picker` that is based on `Umbraco.MediaPicker3` indexed the result as show in [this](https://www.youtube.com/watch?v=mCMB4bjmGXA&ab_channel=UmbracoDXP) video, with this JSON value: `[{"key":"b0567635-3f07-4b32-b636-55b965a47081","mediaKey":"55514845-b8bd-487c-b370-9724852fd6bb"}]`.

Thanks,
Adrian

**Comment by d-gibbs** [comment]
Hi @acoumb

That document type is using a control based on the `Umbraco.MediaPicker3`:

![image](https://user-images.githubusercontent.com/59481722/218494676-170450f4-e065-4207-ba64-7c18e3bdaf87.png)

![image](https://user-images.githubusercontent.com/59481722/218495143-22891559-4f9c-4c64-99ff-ffc72fe3e53f.png)

Field in algolia:

![image](https://user-images.githubusercontent.com/59481722/218495297-bddc0ddb-60e5-466b-b833-6e10fd4630a8.png)

FWIW, we are using models builder which is set to `SourceCodeManual`.

Thank you

**Comment by acoumb** [comment]
Hi @d-gibbs ,

Please find the updates in version [1.2.0](https://www.nuget.org/packages/Umbraco.Cms.Integrations.Search.Algolia/1.2.0) of the package.

Thank you,
Adrian

**Comment by acoumb** [comment]
Version [1.3.0](https://www.nuget.org/packages/Umbraco.Cms.Integrations.Search.Algolia/1.3.0) is now released, with an updated indexing and [documentation](https://docs.umbraco.com/umbraco-dxp/integrations/algolia).

Closing this for now, but feel free to reach out if you have other input.
