### ISSUE TITLE
Integrations.Search.Algolia - New documents are not being pushed/indexed on save & publish

### ISSUE THREAD

**Issue by d-gibbs** [umbraco/Umbraco.Cms.Integrations#84]
Hi,

I'm using `Umbraco.Cms.Integrations.Search.Algolia 1.1.1` and in the process of implementing site search. I have a basic index which includes two types with a number of fields defined to include against them.

Example:

- Article page
  - Title
  - Body content
  - Image
- Content page
  - Title
  - Body content

I'm finding that creating a new page of either of these document types does not trigger the index to be rebuilt and the new page does not show up as an additional index item when checking [algolia.com](https://algolia.com).

I have also found that changes to existing documents, that are already included in the index, do not get pushed to algolia either e.g. a change to the `Title` or `Body content` field above.

The only way to get these to show up is if I head to `Settings > Algolia Search Management` and manually rebuild the index.

The [readme](https://github.com/umbraco/Umbraco.Cms.Integrations/tree/main/src/Umbraco.Cms.Integrations.Search.Algolia) suggests that:

> The actual content payload is pushed to Algolia for indices created in Umbraco on two scenarios:
> 
> - from the list of indices, the Build action is triggered, resulting in all content of specific document types to be sent as JSON to Algolia.
> - **_using a ContentPublishedNotification handler which will check the list of indices for the specific document type, and will update a matching Algolia object_**

So it seems the plugin should be handling this but something isn't working quite right.

I have checked log viewer and can see the following error raised upon saving a page:

![image](https://user-images.githubusercontent.com/59481722/217572498-c251eae5-1ac6-44dc-9fa2-4fbe6efec09c.png)

If there's any further info you need from me just let me know.

Thank you

**Comment by acoumb** [comment]
Hi @d-gibbs ,

I could not replicate this issue so I tried to retrace your steps as shown in [this](https://www.youtube.com/watch?v=mCMB4bjmGXA&ab_channel=UmbracoDXP) video. 

Could you check my use case and see if in your case there is something different, so I can identify the issue?

Thank you,
Adrian

**Comment by d-gibbs** [comment]
Hi @acoumb 

Thanks for getting back to me. I've attached a screen recording:
https://www.awesomescreenshot.com/video/14772203?key=0da69266847238b73188bde050fd586a

In the video I perform the following actions:

- Show that the document type `Article` is included as an allowed document type
- Show the algolia index in the CMS and Algolia - `GlobalSiteSearch`, note the record count sits at **25**
- Create a new document using the `Article` document type - this should trigger the document to be pushed into Algolia
- I switch back to algolia.com and show that the index has not updated and still sits at a count of **25** records
- I switch back to the CMS and manually rebuild the `GlobalSiteSearch` index
- Finally, I reload algolia.com which now shows an updated record count of **26** 

If I check the log viewer application I can see that an object ref error was thrown via the [BaseContentHandler.cs](https://github.com/umbraco/Umbraco.Cms.Integrations/blob/20df6aa14c5783b887b64e2161dd0d60b3199496/src/Umbraco.Cms.Integrations.Search.Algolia/Handlers/BaseContentHandler.cs) class.

Here's the full log entry:

```
{
   "@t":"2023-02-13T10:09:57.0561370Z",
   "@mt":"Failed to update data for Algolia index: Object reference not set to an instance of an object.",
   "@l":"Error",
   "SourceContext":"Umbraco.Cms.Integrations.Search.Algolia.Handlers.ContentPublishedHandler",
   "ActionId":"9fa8dc1c-6612-420f-b8d6-f1108ced8cc9",
   "ActionName":"Umbraco.Cms.Web.BackOffice.Controllers.ContentController.PostSave (Umbraco.Web.BackOffice)",
   "RequestId":"800001bb-0002-f100-b63f-84710c7967bb",
   "RequestPath":"/umbraco/backoffice/umbracoapi/content/PostSave",
   "ProcessId":32100,
   "ProcessName":"iisexpress",
   "ThreadId":103,
   "ApplicationId":"2d556ea917f58b37b27538f40229032b32fcfd89",
   "MachineName":"06974-LT",
   "Log4NetLevel":"ERROR",
   "HttpRequestId":"871d46a3-9f20-41ad-a9a8-ffef0cfb3a29",
   "HttpRequestNumber":24,
   "HttpSessionId":"e8323eab-870f-5ece-e170-83722c898f73"
}
```

Please let me know if there's anything else I can provide.

Thank you

**Comment by acoumb** [comment]
Version [1.3.0](https://www.nuget.org/packages/Umbraco.Cms.Integrations.Search.Algolia/1.3.0) is now released, with an updated indexing and [documentation](https://docs.umbraco.com/umbraco-dxp/integrations/algolia).

Closing this for now, but feel free to reach out if you have other input.
