### ISSUE TITLE
Integrations.Search.Algolia - Include document URL with indexed item

### ISSUE THREAD

**Issue by d-gibbs** [umbraco/Umbraco.Cms.Integrations#85]
Hi,

I'm using `Umbraco.Cms.Integrations.Search.Algolia 1.1.1` and in the process of implementing site search.

I have found that there is no ability to select a document URL when choosing which fields to index for a given type.

For example - I've created a basic document type which has a single property `Title`:

![image](https://user-images.githubusercontent.com/59481722/217574042-7598ea1e-a162-4a7d-859f-331986873bc6.png)

And the index definition includes the single property as expected:

![image](https://user-images.githubusercontent.com/59481722/217574208-6cc41bb0-0ae3-40ad-b136-6063d3555b46.png)

But you get nothing else other than this. I feel to be useful, the index item at a minimum should include a URL to the page. Without this, we'd need to perform lookups on the items coming back in order to be able to give the user a link to the search result.

Could the indexer include the document URL as default OR can you provide the option to pick default umbraco fields (as well custom properties) to include e.g. content type, culture, url, id etc... ?

Thank you

**Comment by chris-evansnz** [comment]
@acoumb in addition to URL it would be good to get the node Name as well

**Comment by tony-gledhill** [comment]
Please can we include the node created and updated dates.

**Comment by acoumb** [comment]
Hi @d-gibbs , @chris-evansnz , @tony-gledhill ,

Version [1.2.0](https://www.nuget.org/packages/Umbraco.Cms.Integrations.Search.Algolia/1.2.0) of the package contains the additional properties.

Thank you,
Adrian

**Comment by tony-gledhill** [comment]
Thanks @acoumb - I'm installing now ! 👍 H5YR

**Comment by acoumb** [comment]
Version [1.3.0](https://www.nuget.org/packages/Umbraco.Cms.Integrations.Search.Algolia/1.3.0) is now released, with an updated indexing and [documentation](https://docs.umbraco.com/umbraco-dxp/integrations/algolia).

Closing this for now, but feel free to reach out if you have other input.
