### ISSUE TITLE
No forms in the form picker

### ISSUE THREAD

**Issue by daanbakker1995** [umbraco/Umbraco.Cms.Integrations#89]
Hi Umbraco team,

We have an Umbraco website with version `version 10.3.2` and are using The Umbraco.Cms.Integrations.Crm.Dynamics nuget package version `1.1.3`. 

The Issue we are having is that no forms are showing in the dynamic form picker. There are no forms showing up to be used. A thing i noticed is that in the Network tab there are timeouts showing. 
![image](https://user-images.githubusercontent.com/15106898/225011114-e6abade5-2d60-41ba-9124-f10126df9f98.png)

Do you have any idea what we could be doing wrong here? 

I have configured the package in the app settings with the following configurations. 
![image](https://user-images.githubusercontent.com/15106898/225010097-3297dcd6-db21-4032-bd57-dd3e986ed9a0.png)

Our customer has followed the installation instructions provided in the blog post of their Dynamics account.
Blog: https://umbraco.com/blog/integrating-umbraco-cms-with-microsoft-dynamics-365-marketing-forms/

Then they have connected with an admin account in the Umbraco website. The revoke option is also not showing.

Greetings,
Daan

**Comment by acoumb** [comment]
Hi @daanbakker1995 ,

Do you mean that the _Revoke_ button is not visible, or disabled like this:
![image](https://user-images.githubusercontent.com/95346674/225621362-ec1501e7-1dab-425e-8363-4c12f12bfcd2.png)

If disabled, then you did not connect successfully to your Dynamics instance.

Also, the forms hosted on Dynamics need to be published and _hosted_ to be accessible from Umbraco. [Here](https://learn.microsoft.com/en-us/dynamics365/marketing/embed-forms) is some documentation on this.

Thank you,
Adrian

**Comment by daanbakker1995** [comment]
Hi @acoumb,

The problem is not that the Revoke is disabled.
The problem is that the revoke and the connect are not showing.
<img width="859" alt="image" src="https://user-images.githubusercontent.com/15106898/225856069-68f28aaf-bdae-4d60-b677-29bdc018e60d.png">

**Comment by acoumb** [comment]
Hi,

Which version of Umbraco are you using? Also, is it a Cloud instance?

Thanks

**Comment by daanbakker1995** [comment]
The umbraco version is 10.2.3 and it's not an Umbraco cloud project if that's what you're refering to. It is hosted on Azure.

**Comment by acoumb** [comment]
Hi @daanbakker1995 ,

Could you tell me if you still encounter issues based on my last comment?

Thanks

**Comment by daanbakker1995** [comment]
This issue seemed to have been solved. The connection buttons show up again. The thing i did to solve it was uninstall the old and install the newer version. There is however a issue that the connection will disconnect a lot but for that i will create a new issue.
