### ISSUE TITLE
Connection keeps disconnecting

### ISSUE THREAD

**Issue by daanbakker1995** [umbraco/Umbraco.Cms.Integrations#99]
Hi there.

I'm having an issue were the connection that has been made is disconnected. Somehow this happens but there are no logs I can find to trace this issue. Is this an commen issue or is it just me? 

When connected i was able to select Dynamic forms. The seting haven't change since.

I'm using an Umbraco website with version `10.4.0`. The package version is `1.2.0`. 

Any idea what might cause this problem?

See below the message I'm getting after i have been connected.
<img width="702" alt="image" src="https://user-images.githubusercontent.com/15106898/235083016-0d3feb63-6bf6-4087-8220-3c8cb22bd983.png">

**Comment by acoumb** [comment]
Hi @daanbakker1995 ,

I will look into this and see what has happened. 
Does it give you the _Connected_ status in the configuration view of the data type?

Thanks you,
Adrian

**Comment by daanbakker1995** [comment]
Hi @acoumb,

Thanks a lot for replying so fast. No the status is not connected it show the disconnected status. We have tried to connect multiple times. That works for a while and then it disconnects for some reason. 

Our customer needs to do the connection due to authorization reasons. They mentioned that the connection also disconnected after pressing the save button. I think this happens because on save the authentication happens again. 

<img width="706" alt="image" src="https://user-images.githubusercontent.com/15106898/235084134-a7bf08c4-04c3-46a5-a678-c69f3a8003a5.png">

**Comment by acoumb** [comment]
Could you tell me if they can get authorized with their Microsoft account, or if they receive some kind of notification when trying to login?
Maybe could you ask them to clear the cache and resume the login process and watching if they are prompted by the Umbraco App and then registered?

**Comment by daanbakker1995** [comment]
As far as i know they connected with an Microsoft account and they got a pop-up screen to verify their Microsoft login. 

I have applied for a personal account to their Microsoft organisation. I hope when the provide that to me i can check i out for myself. I'll keep you updated.

**Comment by acoumb** [comment]
Also keep in mind that with the latest package update we've introduced the _OAuth Self Hosted_ concept, where you can use your own Azure App to handle authorizations.

You can read more about this on [Umbraco Docs](https://docs.umbraco.com/umbraco-dxp/integrations/dynamics#self-hosted-oauth-configuration).

**Comment by daanbakker1995** [comment]
Thanks for the tip. Once this issue won't be solved that's someting we will try!

Greetings.

**Comment by acoumb** [comment]
Hi @daanbakker1995 ,

I am closing this now, but you have other input, please feel free to reach out.

Thank you,
Adrian
